version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/ var/lib/mysql

volumes:
  mysql_data: